export * from './IUser';
export * from './IGroup';
export * from './ITimeTable';
export * from './IDayOfWeek';
export * from './ILesson';
export * from './IDiscipline';
export * from './ITeacher';
export * from './IClassRoom';
export * from './IArticle';
